export const API_URLS = {
  GOOGLE: `/auth/google`,
  STUDENTS: `/students`,
  STUDENTS_BY_STUDY: `/students/study`,
  UNSUBSCRIBE_STUDENTS: `/students/unsubscribe`,
  PROJECTS: `/projects`,
  SCHOOL_PROJECTS: `/projects/centre`,
  STUDENT_PROJECTS: `/projects/alumn`,
  MODULES: `/curr-moduls`,
  CONFIRM_MODULES: `/selected-moduls`,
  STUDIES: `/group_study`,
  CONFIG: `/config`,
  COURSES: '/cursos-grups',
  PROJECT_MODULE_DATES: '/dates-modul-projectes',
  SCHEDULE: '/schedule',
  RUBRICS: {
    BASE: `/rubrics`,
    COURSES: `/rubrics/courses`,
    CRITERIA: `/rubrics/criteris`,
    RUBRIC_CRITERION: '/rubric-criterion',
    RUBRIC_LEVEL: '/rubrics/levels',
  },
  CALENDAR_EVENTS: `/calendar-events`,
}
